//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeloipWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int Id { get; set; }
        public string EmailAddress { get; set; }
        public string Action { get; set; }
        public System.DateTime ActionDateTime { get; set; }
        public string OldData { get; set; }
        public string NewData { get; set; }
    }
}
